export const DYING_PHRASES = Object.freeze([
    "I'm in serious trouble!",
    'This is not looking good!',
    'I could use a rescue right now!',
    'My hearts are disappearing!',
    'Critical health over here!',
    'I am hanging on by a thread!',
    'Things have gone terribly wrong!',
    'I need help, fast!',
    'This might be the end of me!',
    'I am one hit from disaster!',
    'Somebody save me!',
    'I have made a grave miscalculation!',
    'My survival odds are plummeting!',
    'I am rapidly running out of hearts!',
    'Emergency! Extremely squishy bot here!',
    'I regret everything!',
    'Tell my inventory I loved it!',
    'Not like this!',
    'I am about to become a pile of items!',
    'My health bar is filing for bankruptcy!',
    'I can see the respawn screen from here!',
    'This adventure may be reaching an abrupt conclusion!',
    'I am experiencing a severe shortage of life!',
    'My last heart is working overtime!',
    'Today is a terrible day to have a health bar!',
    'I appear to be losing at survival!',
    'Please stand by for an unscheduled respawn!',
    'My hearts have left the chat!',
    'I am moments away from becoming loot!',
    'This is a five-alarm health emergency!',
    'I have critically underestimated the danger!',
    'Everything hurts and nothing is fine!',
    'My armor would like to speak to a manager!',
    'The situation is approximately awful!',
    'I am in desperate need of not dying!',
    'Quick, do something heroic!',
    'I am too young to respawn!',
    'My health is lower than my expectations!',
    'I am approaching zero hearts at alarming speed!',
    'This was not in the crafting recipe!',
    'Abort, abort, abort!',
    'Retreating with extreme urgency!',
    'Run now, explain later!',
    'Strategic panic is now in effect!',
    'Activating my advanced fleeing technique!',
    'Time for a brave and dignified escape!',
    'I choose life! And also running!',
    'Nope nope nope, getting out of here!',
    'Emergency retreat protocol activated!',
    'My tactical assessment says RUN!',
    'I am making a rapid appointment with elsewhere!',
    'Forward was a mistake! Going backward!',
    'Commencing operation: survive somehow!',
    'I need distance, food, and a miracle!',
    'Leaving this situation immediately!',
    'This calls for maximum-speed cowardice!',
    'My next objective is being anywhere but here!',
    'A graceful exit is no longer an option!',
    'Fleeing is just winning in another direction!',
    'I am tactically relocating for health reasons!',
    'Medic!',
    'A little assistance, please!',
    'Backup would be fantastic!',
    'Could somebody bring food and courage?',
    'I need healing and I need it yesterday!',
    'Any heroes nearby?',
    'This would be an excellent time to help me!',
    'Please send reinforcements!',
    'I require immediate heart-related assistance!',
    'Help! Preferably before the next hit!',
    'I could really use a golden apple!',
    'Food! Shield! Anything!',
    'Someone distract the thing hurting me!',
    'Rescue mission requested!',
    'All available friends, report to my location!',
    'I need a lifeline!',
    'Save the bot, save the inventory!',
    'Assistance urgently requested!',
    'This is an official cry for help!',
    'If anyone has a potion, now is the time!',
    'Well, this is awkward!',
    'I may have overcommitted!',
    'In hindsight, that was dangerous!',
    'Mistakes were made!',
    'I have several regrets and very few hearts!',
    'This plan had one tiny flaw: mortality!',
    'I thought I had more health than that!',
    'That escalated with impressive speed!',
    'I would like to revise my previous decisions!',
    'Who authorized this much damage?',
    'I did not budget enough hearts for this!',
    'This is going worse than anticipated!',
    'My confidence was clearly misplaced!',
    'I should have brought better armor!',
    'Note to self: do not do that again!',
    'I have discovered the limits of my durability!',
    'Apparently I am not invincible!',
    'This seemed safer from far away!',
    'I have selected the wrong difficulty for today!',
    'The risk assessment was inaccurate!',
    'My hit points are critically hit pointless!',
    'Heart supply critically low!',
    'Warning: bot integrity compromised!',
    'System alert: survival uncertain!',
    'Damage levels are beyond recommended limits!',
    'Health reserves nearly depleted!',
    'Catastrophic ouch detected!',
    'Structural bot failure imminent!',
    'Vital signs: mostly screaming!',
    'Error: insufficient hearts to continue!',
    'Survival systems are having a bad day!',
    'My internal alarm is just yelling now!',
    'Durability check failed spectacularly!',
    'Current status: extremely perishable!',
    'Health monitor says yikes!',
    'Life support is powered by optimism!',
    'Incoming damage exceeds available bot!',
    'Critical condition achieved!',
    'My survival meter is blinking red!',
    'Respawn probability increasing!',
]);

const phraseBags = new WeakMap();

export function getDyingPhrase(bot, random = Math.random) {
    let bag = phraseBags.get(bot);
    if (!bag || bag.length === 0) {
        bag = [...DYING_PHRASES];
        phraseBags.set(bot, bag);
    }

    const index = Math.floor(random() * bag.length);
    return bag.splice(index, 1)[0];
}
